app/models.py
from flask_login import UserMixin
from . import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash

class Pitch(db.Model):

    __tablename__ = 'pitchs'

    id = db.Column(db.Integer, primary_key = True)
    category = db.Column(db.String)
    pitch = db.Column(db.String)
    user_id =db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref = 'pitch', lazy = 'dynamic')



    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls,cat):
        pitch = Pitch.query.filter_by(category=cat).all()
        return pitch

class User(UserMixin, db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    pass_secure = db.Column(db.String(255))  # to store passwords
    pitch = db.relationship('Pitch', backref = 'username', lazy = 'dynamic')
    comments = db.relationship('Comment',backref = 'username', lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)



    def __repr__(self):
        return f' {self.username}'

class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    pitchs_id = db.Column(db.Integer, db.ForeignKey("pitchs.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls,id):
        comment = Comment.query.filter_by(pitchs_id=id).all()
        return comment

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    category = SelectField(u'Pitch Category', choices=[('business', 'business'), ('pick-up', 'pick-up'), ('interview', 'interview')])
    pitch = TextAreaField('Your Pitch')
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):

    comment = TextAreaField('Your Comment')
    submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config_options

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):

    app = Flask(__name__)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    
    app.config.from_object(config_options[config_name])

    
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template, redirect, url_for
from flask_login import login_required, current_user
from . import main
from .forms import PitchForm, CommentForm
from ..models import Pitch, Comment
from ..auth.forms import RegistrationForm

@main.route('/')
def index():
    '''
    function that returns index and its content
    '''
    form = RegistrationForm()
    return render_template('index.html', registration_form = form)

@main.route('/home')
def home():
    '''
    function that returns root.html page and its content
    '''
    title = 'Home' 
    return render_template('root.html', title = title)

@main.route('/pitch/<cat>')
def category(cat):
    '''
    function to return the pitches
    '''
    category = Pitch.get_pitch(cat)
    print(category)
    title = f'{cat}'
    return render_template('pitch.html',title = title, category = category)

@main.route('/new-pitch',methods = ['GET', 'POST'])
@login_required
def new_pitch():
    form = PitchForm()

    if form.validate_on_submit():
        cat = form.category.data
        pich = form.pitch.data

        new_pitch = Pitch(category = cat, pitch = pich, user_id = current_user.id)

        new_pitch.save_pitch()

        return redirect(url_for('main.home'))

    title = 'New Pitch'
    return render_template('new_pitch.html', title=title, pitch_form = form)

@main.route('/comment/<id>')
def comment(id):
    '''
    function to return the pitches
    '''
    comment = Comment.get_comment(id)
    print(comment)
    title = 'comments'
    return render_template('comment.html',title = title, comment = comment)

@main.route('/new_comment/<int:id>', methods = ['GET', 'POST'])
def new_comment(id):
    form = CommentForm()

    if form.validate_on_submit():

        com = form.comment.data

        new_comment = Comment(comment = com, user_id = current_user.id, pitchs_id = id)
        new_comment.save_comment()

        return redirect(url_for('main.home'))

    title = 'New Comment'
    return render_template('new_comment.html', title = title, comment_form = form, pitch_id = id)

app/templates/base.html
{% extends 'bootstrap/base.html' %}


{% block navbar %}

  {% include 'navbar.html' %}

{% endblock %}  

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% if title %}
      <title>{{ title }}</title>
    {% else %}
      <title>Welcome to Pitches </title>
    {% endif %}
  </head>
  <body>
    <div class="container">
      {% block content %}
  
      {% endblock %}
    </div>
  </body>
</html>

app/templates/comment.html
{% extends 'base.html' %}
{% block content %}



{% for c in comment %}
<div class="container-fluid">
<div class="card-deck">
  <div class="card">
  <div class="card-title">
    <h5>{{c.author}}</h5>
  </div>
  <div class="card-body">
    <p>{{c.comment}}</p>
  </div>
</div>

</div>
</div>

{% endfor %}
{% endblock %}

app/templates/errors.html
{% extends 'base.html'%}

{% block content %}
   <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
<!-- <h1> App Works </h1> -->

{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">

{{wtf.quick_form(registration_form)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}

app/templates/navbar.html
 
<nav class="navbar navbar-expand-lg navbar-light" style="background:rgba(0, 255, 213, 0.849);">
  <a class="navbar-brand" href="/">Pitch</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/pitch/business">Business </a>
          <a class="dropdown-item" href="/pitch/pick-up">Pick-up</a>
          <a class="dropdown-item" href="/pitch/interview">interview</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
    </ul>
    <div>
     <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('main.new_pitch') }}">New Post</a>
            <a class="nav-item nav-link" href="{{ url_for('auth.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{{url_for('auth.login')}}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
          {% endif %}
        </div>
  </div>
</nav>

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">

      {{ wtf.quick_form(comment_form) }}

    </div>

{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">

      {{ wtf.quick_form(pitch_form) }}

    </div>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html' %}
{% block content %}

{% for c in category [::-1] %}
<div class="container-fluid">
<div class="card-deck">
  <div class="card">
  <div class="card-title">
    <h5>{{c.category}}</h5>
  </div>
  <div class="card-body">
    <p>{{c.pitch}}</p>
    <p>written by {{c.username}}</p>
    <a href="/comment/{{c.id}}">View Comments</a>
  </div>
  <div class="card-footer">
    <a class="btn btn-primary btn-md" href="/new_comment/{{c.id}}">Add Comment</a>
  </div>
</div>

</div>
</div>

{% endfor %}
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
       
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        
    </div>
{% endblock content %}

app/templates/root.html
{% extends 'base.html' %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static',filename='css/root.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
{% endblock %}

{% block content %}
<div class="row">
  <div class="container">
    <div class="quote">
      <a href="/new-pitch">
          <h5><span>Write Pitch</span></h5>
      </a>
    </div>
    <div class="quote">
      <a href="/pitch/business">
          <h5><span>Business Pitches</span></h5>
      </a>
    </div>
    <div class="quote">
      <a href="/pitch/pick-up">
          <h5><span>Pick-up lines</span></h5>
      </a>
    </div>
    <div class="quote">
      <a href="/pitch/interview">
          <h5><span>Job-interview Pitches</span></h5>
      </a>
    </div>
  </div>
</div>
{% endblock %}